# Use the latest 2.1 version of CircleCI pipeline processing engine, see https://circleci.com/docs/2.0/configuration-reference/
version: 2.1

jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - run:
          name: run build
          command: |
            go build -v
  test:
    pre:
      - go get github.com/mattn/goveralls
    override:
      - go test -v -cover -race -coverprofile=/home/ubuntu/coverage.out
    post:
      - /home/ubuntu/.go_workspace/bin/goveralls -coverprofile=/home/ubuntu/coverage.out -service=circle-ci -repotoken=$COVERALLS_TOKEN
